services:
  - type: web
    plan: free
    name: web-app
    runtime: node
    repo: https://github.com/Carter2307/tp-4esgi-render.git
    startCommand: "npm start"
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: users-db
          property: connectionString

databases:
  - name: users-db 
    plan: free